export const data = JSON.parse("{\"key\":\"v-3c9b67e4\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Crypt/KeyRing.html\",\"title\":\"KeyRing\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Class KeyRing A collection of cryptographic keys. Full name: \\\\Ninja\\\\Cosmic\\\\Crypt\\\\KeyRing; Properties keys type Methods __construct KeyRing constructor. Parameters: Parameter Typ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Crypt/KeyRing.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"KeyRing\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Class KeyRing A collection of cryptographic keys. Full name: \\\\Ninja\\\\Cosmic\\\\Crypt\\\\KeyRing; Properties keys type Methods __construct KeyRing constructor. Parameters: Parameter Typ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"KeyRing\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Properties\",\"slug\":\"properties\",\"link\":\"#properties\",\"children\":[{\"level\":3,\"title\":\"keys\",\"slug\":\"keys\",\"link\":\"#keys\",\"children\":[]},{\"level\":3,\"title\":\"type\",\"slug\":\"type\",\"link\":\"#type\",\"children\":[]}]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"__construct\",\"slug\":\"construct\",\"link\":\"#construct\",\"children\":[]},{\"level\":3,\"title\":\"public\",\"slug\":\"public\",\"link\":\"#public\",\"children\":[]},{\"level\":3,\"title\":\"secret\",\"slug\":\"secret\",\"link\":\"#secret\",\"children\":[]},{\"level\":3,\"title\":\"type\",\"slug\":\"type-1\",\"link\":\"#type-1\",\"children\":[]},{\"level\":3,\"title\":\"count\",\"slug\":\"count\",\"link\":\"#count\",\"children\":[]},{\"level\":3,\"title\":\"isEmpty\",\"slug\":\"isempty\",\"link\":\"#isempty\",\"children\":[]},{\"level\":3,\"title\":\"all\",\"slug\":\"all\",\"link\":\"#all\",\"children\":[]},{\"level\":3,\"title\":\"add\",\"slug\":\"add\",\"link\":\"#add\",\"children\":[]},{\"level\":3,\"title\":\"get\",\"slug\":\"get\",\"link\":\"#get\",\"children\":[]},{\"level\":3,\"title\":\"has\",\"slug\":\"has\",\"link\":\"#has\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.03,\"words\":310},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Crypt/KeyRing.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
