export const data = JSON.parse("{\"key\":\"v-4f4e4f96\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Terminal/Input/Select/Input/SelectInputInterface.html\",\"title\":\"SelectInputInterface\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Input\\\\Select\\\\Input\\\\SelectInputInterface; Methods getMessage getOptions getSelections hasSelections isSelected Parameters: Parameter Type Descri...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Terminal/Input/Select/Input/SelectInputInterface.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"SelectInputInterface\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Input\\\\Select\\\\Input\\\\SelectInputInterface; Methods getMessage getOptions getSelections hasSelections isSelected Parameters: Parameter Type Descri...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"SelectInputInterface\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"getMessage\",\"slug\":\"getmessage\",\"link\":\"#getmessage\",\"children\":[]},{\"level\":3,\"title\":\"getOptions\",\"slug\":\"getoptions\",\"link\":\"#getoptions\",\"children\":[]},{\"level\":3,\"title\":\"getSelections\",\"slug\":\"getselections\",\"link\":\"#getselections\",\"children\":[]},{\"level\":3,\"title\":\"hasSelections\",\"slug\":\"hasselections\",\"link\":\"#hasselections\",\"children\":[]},{\"level\":3,\"title\":\"isSelected\",\"slug\":\"isselected\",\"link\":\"#isselected\",\"children\":[]},{\"level\":3,\"title\":\"select\",\"slug\":\"select\",\"link\":\"#select\",\"children\":[]},{\"level\":3,\"title\":\"deselect\",\"slug\":\"deselect\",\"link\":\"#deselect\",\"children\":[]},{\"level\":3,\"title\":\"controlMode\",\"slug\":\"controlmode\",\"link\":\"#controlmode\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.27,\"words\":81},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Terminal/Input/Select/Input/SelectInputInterface.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
