export const data = JSON.parse("{\"key\":\"v-ac08c1d2\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Terminal/Theme/Element/Color/ColorCollection.html\",\"title\":\"ColorCollection\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\Color\\\\ColorCollection; Parent class: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\AbstractElementCollection (../AbstractElementCollection...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Terminal/Theme/Element/Color/ColorCollection.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ColorCollection\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\Color\\\\ColorCollection; Parent class: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\AbstractElementCollection (../AbstractElementCollection...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ColorCollection\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"getType\",\"slug\":\"gettype\",\"link\":\"#gettype\",\"children\":[]},{\"level\":3,\"title\":\"getCollectionType\",\"slug\":\"getcollectiontype\",\"link\":\"#getcollectiontype\",\"children\":[]},{\"level\":3,\"title\":\"toArray\",\"slug\":\"toarray\",\"link\":\"#toarray\",\"children\":[]},{\"level\":3,\"title\":\"fromArray\",\"slug\":\"fromarray\",\"link\":\"#fromarray\",\"children\":[]},{\"level\":3,\"title\":\"color\",\"slug\":\"color\",\"link\":\"#color\",\"children\":[]},{\"level\":3,\"title\":\"load\",\"slug\":\"load\",\"link\":\"#load\",\"children\":[]},{\"level\":3,\"title\":\"fromFile\",\"slug\":\"fromfile\",\"link\":\"#fromfile\",\"children\":[]}]},{\"level\":2,\"title\":\"Inherited methods\",\"slug\":\"inherited-methods\",\"link\":\"#inherited-methods\",\"children\":[{\"level\":3,\"title\":\"getType\",\"slug\":\"gettype-1\",\"link\":\"#gettype-1\",\"children\":[]},{\"level\":3,\"title\":\"getCollectionType\",\"slug\":\"getcollectiontype-1\",\"link\":\"#getcollectiontype-1\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.52,\"words\":156},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Terminal/Theme/Element/Color/ColorCollection.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
