export const data = JSON.parse("{\"key\":\"v-1c43756a\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Terminal/Input/Select/Input/Trait/ColumnableOptionTrait.html\",\"title\":\"ColumnableOptionTrait\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Input\\\\Select\\\\Input\\\\Trait\\\\ColumnableOptionTrait; Properties columns columnSize Methods getColumns Parameters: Parameter Type Description -------...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Terminal/Input/Select/Input/Trait/ColumnableOptionTrait.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ColumnableOptionTrait\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Input\\\\Select\\\\Input\\\\Trait\\\\ColumnableOptionTrait; Properties columns columnSize Methods getColumns Parameters: Parameter Type Description -------...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ColumnableOptionTrait\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Properties\",\"slug\":\"properties\",\"link\":\"#properties\",\"children\":[{\"level\":3,\"title\":\"columns\",\"slug\":\"columns\",\"link\":\"#columns\",\"children\":[]},{\"level\":3,\"title\":\"columnSize\",\"slug\":\"columnsize\",\"link\":\"#columnsize\",\"children\":[]}]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"getColumns\",\"slug\":\"getcolumns\",\"link\":\"#getcolumns\",\"children\":[]},{\"level\":3,\"title\":\"getColumnAt\",\"slug\":\"getcolumnat\",\"link\":\"#getcolumnat\",\"children\":[]},{\"level\":3,\"title\":\"getColumnCount\",\"slug\":\"getcolumncount\",\"link\":\"#getcolumncount\",\"children\":[]},{\"level\":3,\"title\":\"hasEntryAt\",\"slug\":\"hasentryat\",\"link\":\"#hasentryat\",\"children\":[]},{\"level\":3,\"title\":\"getEntryAt\",\"slug\":\"getentryat\",\"link\":\"#getentryat\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.34,\"words\":102},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Terminal/Input/Select/Input/Trait/ColumnableOptionTrait.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
