export const data = JSON.parse("{\"key\":\"v-1ad37682\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Terminal/Descriptor/AbstractDescriptor.html\",\"title\":\"AbstractDescriptor\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Descriptor\\\\AbstractDescriptor; This class implements:; \\\\Symfony\\\\Component\\\\Console\\\\Descriptor\\\\DescriptorInterface (../../../../Symfony/Component...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Terminal/Descriptor/AbstractDescriptor.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"AbstractDescriptor\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Descriptor\\\\AbstractDescriptor; This class implements:; \\\\Symfony\\\\Component\\\\Console\\\\Descriptor\\\\DescriptorInterface (../../../../Symfony/Component...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"AbstractDescriptor\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Properties\",\"slug\":\"properties\",\"link\":\"#properties\",\"children\":[{\"level\":3,\"title\":\"output\",\"slug\":\"output\",\"link\":\"#output\",\"children\":[]}]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"describe\",\"slug\":\"describe\",\"link\":\"#describe\",\"children\":[]},{\"level\":3,\"title\":\"write\",\"slug\":\"write\",\"link\":\"#write\",\"children\":[]},{\"level\":3,\"title\":\"describeInputArgument\",\"slug\":\"describeinputargument\",\"link\":\"#describeinputargument\",\"children\":[]},{\"level\":3,\"title\":\"describeInputOption\",\"slug\":\"describeinputoption\",\"link\":\"#describeinputoption\",\"children\":[]},{\"level\":3,\"title\":\"describeInputDefinition\",\"slug\":\"describeinputdefinition\",\"link\":\"#describeinputdefinition\",\"children\":[]},{\"level\":3,\"title\":\"describeCommand\",\"slug\":\"describecommand\",\"link\":\"#describecommand\",\"children\":[]},{\"level\":3,\"title\":\"describeApplication\",\"slug\":\"describeapplication\",\"link\":\"#describeapplication\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.85,\"words\":255},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Terminal/Descriptor/AbstractDescriptor.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
