export const data = JSON.parse("{\"key\":\"v-62430d61\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Replacer/AbstractReplacer.html\",\"title\":\"AbstractReplacer\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Replacer\\\\AbstractReplacer; This class implements:; \\\\Ninja\\\\Cosmic\\\\Replacer\\\\ReplacerInterface (./ReplacerInterface.md) This class is an Abstract class; Co...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Replacer/AbstractReplacer.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"AbstractReplacer\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Replacer\\\\AbstractReplacer; This class implements:; \\\\Ninja\\\\Cosmic\\\\Replacer\\\\ReplacerInterface (./ReplacerInterface.md) This class is an Abstract class; Co...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"AbstractReplacer\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Constants\",\"slug\":\"constants\",\"link\":\"#constants\",\"children\":[]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"replace\",\"slug\":\"replace\",\"link\":\"#replace\",\"children\":[]},{\"level\":3,\"title\":\"__construct\",\"slug\":\"construct\",\"link\":\"#construct\",\"children\":[]},{\"level\":3,\"title\":\"extractPlaceholders\",\"slug\":\"extractplaceholders\",\"link\":\"#extractplaceholders\",\"children\":[]},{\"level\":3,\"title\":\"replacePlaceholder\",\"slug\":\"replaceplaceholder\",\"link\":\"#replaceplaceholder\",\"children\":[]},{\"level\":3,\"title\":\"getPrefix\",\"slug\":\"getprefix\",\"link\":\"#getprefix\",\"children\":[]},{\"level\":3,\"title\":\"getPlaceholderValue\",\"slug\":\"getplaceholdervalue\",\"link\":\"#getplaceholdervalue\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.38,\"words\":114},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Replacer/AbstractReplacer.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
