<template><div><h1 id="🔫-lifecycle-events" tabindex="-1"><a class="header-anchor" href="#🔫-lifecycle-events" aria-hidden="true">#</a> 🔫 Lifecycle Events</h1>
<h2 id="what-is-a-lifecycle-event" tabindex="-1"><a class="header-anchor" href="#what-is-a-lifecycle-event" aria-hidden="true">#</a> What is a Lifecycle Event?</h2>
<p>In the context of the <code v-pre>Ninja\Cosmic\Event</code> namespace, a lifecycle event is a significant occurrence in the life of an object that is part of the application. These events are defined and dispatched by the application, and they can be listened to by other parts of the application.</p>
<p>Lifecycle events are identified by a string name, and they can carry additional data in the form of an associative array. The lifecycle event name and its data are encapsulated in a <code v-pre>LifecycleEventArgs</code> object.</p>
<h2 id="what-is-a-listener" tabindex="-1"><a class="header-anchor" href="#what-is-a-listener" aria-hidden="true">#</a> What is a Listener?</h2>
<p>A listener is a callable or an object implementing the <code v-pre>LifecycleEventListenerInterface</code> that is registered to a lifecycle event. When the event is dispatched, the listener is invoked with the <code v-pre>LifecycleEventArgs</code> object as an argument.</p>
<h2 id="dispatching-an-event" tabindex="-1"><a class="header-anchor" href="#dispatching-an-event" aria-hidden="true">#</a> Dispatching an event</h2>
<p>Dispatching a lifecycle event is done by calling the <code v-pre>dispatchLifecycleEvent</code> static method on the <code v-pre>LifecycleAwareInterface</code> with the event name and an array of event arguments. The method will iterate over all registered listeners for the event and invoke them with a <code v-pre>LifecycleEventArgs</code> object.</p>
<h2 id="registering-and-executing-a-listener" tabindex="-1"><a class="header-anchor" href="#registering-and-executing-a-listener" aria-hidden="true">#</a> Registering and executing a listener</h2>
<p>A listener can be registered to a lifecycle event by calling the <code v-pre>registerListener</code> static method on the <code v-pre>LifecycleAwareInterface</code>. The method accepts the event name (or an array of event names) and the listener. The listener can be a callable or an object implementing the <code v-pre>LifecycleEventListenerInterface</code>.</p>
<p>When a lifecycle event is dispatched, all its registered listeners are executed. Each listener is invoked with a <code v-pre>LifecycleEventArgs</code> object.</p>
<h2 id="defined-lifecycle-events" tabindex="-1"><a class="header-anchor" href="#defined-lifecycle-events" aria-hidden="true">#</a> Defined Lifecycle Events</h2>
<p>The specific lifecycle events that are defined and when they occur depend on the application. They are registered by calling the <code v-pre>registerLifecycleEvents</code> static method on the <code v-pre>LifecycleAwareInterface</code> with an array of event names.</p>
<p>The <code v-pre>LifecycleAwareInterface</code> does not define any specific lifecycle events. Instead, it provides the mechanism for registering and dispatching lifecycle events. The actual lifecycle events are defined by the application.</p>
<p>It is a recommended practice to register a minimal set of lifecycle events on application bootstrap time, the applications generated with cosmic init command, define the following set of events in the file lifecycle.php located in /bootstrap folder</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token php language-php"><span class="token delimiter important">&lt;?php</span>  
  
<span class="token keyword">declare</span><span class="token punctuation">(</span>strict_types<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  
  
<span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Application<span class="token punctuation">\</span>Application</span><span class="token punctuation">;</span>  
<span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Command<span class="token punctuation">\</span>CommandInterface</span><span class="token punctuation">;</span>  
<span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Event<span class="token punctuation">\</span>Lifecycle</span><span class="token punctuation">;</span>  
<span class="token keyword">use</span> <span class="token package">Ramsey<span class="token punctuation">\</span>Uuid<span class="token punctuation">\</span>Uuid</span><span class="token punctuation">;</span>  
  
<span class="token punctuation">(</span><span class="token keyword">static</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword return-type">void</span> <span class="token punctuation">{</span>  
    <span class="token class-name static-context">Lifecycle</span><span class="token operator">::</span><span class="token function">withLifecycleId</span><span class="token punctuation">(</span><span class="token class-name static-context">Uuid</span><span class="token operator">::</span><span class="token function">uuid7</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  
    <span class="token class-name static-context">Lifecycle</span><span class="token operator">::</span><span class="token function">registerLifecycleEvents</span><span class="token punctuation">(</span><span class="token punctuation">[</span>  
        <span class="token class-name static-context">Application</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_APP_BOOT</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">Application</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_APP_SHUTDOWN</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">Application</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_APP_BUILD</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">Application</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_APP_INSTALL</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">CommandInterface</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_COMMAND_RUN</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">CommandInterface</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_COMMAND_SUCCESS</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">CommandInterface</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_COMMAND_FAILURE</span><span class="token punctuation">,</span>  
        <span class="token class-name static-context">CommandInterface</span><span class="token operator">::</span><span class="token constant">LIFECYCLE_COMMAND_ERROR</span>  
    <span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="lifecycleeventargs-class" tabindex="-1"><a class="header-anchor" href="#lifecycleeventargs-class" aria-hidden="true">#</a> LifecycleEventArgs class</h2>
<p>This is used to encapsulate the lifecycle event name, its arguments, and an optional lifecycle ID. It is used as payload to transfer data among the lifecycle event and its listeners.</p>
<h3 id="class-properties" tabindex="-1"><a class="header-anchor" href="#class-properties" aria-hidden="true">#</a> Class Properties</h3>
<p>The class has three properties:</p>
<ul>
<li><code v-pre>lifecycle_event</code>: A string representing the lifecycle event name.</li>
<li><code v-pre>args</code>: An array holding the arguments of the lifecycle event.</li>
<li><code v-pre>lifecycle_id</code>: An optional UUID representing the lifecycle ID.</li>
</ul>
<h2 id="magic-methods" tabindex="-1"><a class="header-anchor" href="#magic-methods" aria-hidden="true">#</a> Magic Methods</h2>
<p>The class uses the magic <code v-pre>__call</code> method to provide dynamic getter and setter methods for the <code v-pre>args</code> array.</p>
<h3 id="the-call-method" tabindex="-1"><a class="header-anchor" href="#the-call-method" aria-hidden="true">#</a> The <code v-pre>__call</code> Method</h3>
<p>The <code v-pre>__call</code> method is invoked when an inaccessible method is called on the object. It checks if the method name starts with &quot;get&quot; or &quot;set&quot;. If it does, it treats the method as a getter or setter for the <code v-pre>args</code> array.</p>
<ul>
<li>If the method is a getter (i.e., starts with &quot;get&quot;), it returns the value from the <code v-pre>args</code> array corresponding to the property name.</li>
<li>If the method is a setter (i.e., starts with &quot;set&quot;), it sets the value in the <code v-pre>args</code> array corresponding to the property name.</li>
</ul>
<p>The property name is derived from the method name by removing the &quot;get&quot; or &quot;set&quot; prefix and converting the remaining string to snake case.</p>
<h2 id="other-methods" tabindex="-1"><a class="header-anchor" href="#other-methods" aria-hidden="true">#</a> Other Methods</h2>
<p>The class also has getter methods for the <code v-pre>lifecycle_event</code> and <code v-pre>lifecycle_id</code> properties, and a <code v-pre>getArgs</code> method to return the entire <code v-pre>args</code> array.</p>
<p>Here is a brief example of how you can use the <code v-pre>LifecycleEventArgs</code> class:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// Instantiate the LifecycleEventArgs class</span>
<span class="token variable">$eventArgs</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">LifecycleEventArgs</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'onUserLogin'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'username'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'diego-ninja'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token variable">$uuid</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Use the magic __call method to set a new argument</span>
<span class="token variable">$eventArgs</span><span class="token operator">-></span><span class="token function">setEmail</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'diego-ninja@example.com'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Use the magic __call method to get an argument</span>
<span class="token variable">$email</span> <span class="token operator">=</span> <span class="token variable">$eventArgs</span><span class="token operator">-></span><span class="token function">getEmail</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In the above example, the <code v-pre>setEmail</code> and <code v-pre>getEmail</code> methods do not actually exist in the <code v-pre>LifecycleEventArgs</code> class. They are handled by the <code v-pre>__call</code> method, which treats them as a setter and getter for the <code v-pre>args</code> array, respectively.</p>
<h2 id="working-example" tabindex="-1"><a class="header-anchor" href="#working-example" aria-hidden="true">#</a> Working example</h2>
<p>First, let's define a new lifecycle event. We'll call it <code v-pre>onUserLogin</code>. We can register this event by calling the <code v-pre>registerLifecycleEvents</code> method on the <code v-pre>LifecycleAwareInterface</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">LifecycleAwareInterface</span><span class="token operator">::</span><span class="token function">registerLifecycleEvents</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'onUserLogin'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Next, let's define a listener for this event. A listener can be any callable or an object implementing the <code v-pre>LifecycleEventListenerInterface</code>. For this example, let's create a simple callable listener that prints a message when the event is dispatched.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$listener</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">LifecycleEventArgs</span> <span class="token variable">$args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">echo</span> <span class="token string double-quoted-string">"User with ID <span class="token interpolation"><span class="token punctuation">{</span><span class="token variable">$args</span><span class="token operator">-></span><span class="token function">getUser</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">}</span></span> has logged in."</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Now we can register this listener to the <code v-pre>onUserLogin</code> event by calling the <code v-pre>registerListener</code> method on the <code v-pre>LifecycleAwareInterface</code>.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">LifecycleAwareInterface</span><span class="token operator">::</span><span class="token function">registerListener</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'onUserLogin'</span><span class="token punctuation">,</span> <span class="token variable">$listener</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Now, whenever the <code v-pre>onUserLogin</code> event is dispatched, our listener will be invoked and print a message to the console.</p>
</div></template>


