export const data = JSON.parse("{\"key\":\"v-8545fb40\",\"path\":\"/dev/question.html\",\"title\":\"📝 Question\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"The Question class is a facade that provides a simple interface to complex subsystems in a system. It provides a set of methods that delegate the work to other classes and metho...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/question.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Cosmic PHP - Documentation\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"📝 Question\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"The Question class is a facade that provides a simple interface to complex subsystems in a system. It provides a set of methods that delegate the work to other classes and metho...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Diego Rin Martín\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"📝 Question\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Diego Rin Martín\\\",\\\"url\\\":\\\"https://diego.ninja\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"ask(string $message, ?string $default = null, array $autoComplete = [], bool $decorated = true): ?string\",\"slug\":\"ask-string-message-string-default-null-array-autocomplete-bool-decorated-true-string\",\"link\":\"#ask-string-message-string-default-null-array-autocomplete-bool-decorated-true-string\",\"children\":[]},{\"level\":2,\"title\":\"confirm(string $message, bool $default = true, bool $decorated = true): bool\",\"slug\":\"confirm-string-message-bool-default-true-bool-decorated-true-bool\",\"link\":\"#confirm-string-message-bool-default-true-bool-decorated-true-bool\",\"children\":[]},{\"level\":2,\"title\":\"hidden(string $message, bool $decorated = true): ?string\",\"slug\":\"hidden-string-message-bool-decorated-true-string\",\"link\":\"#hidden-string-message-bool-decorated-true-string\",\"children\":[]},{\"level\":2,\"title\":\"select(string $message, array $options, bool $allowMultiple = true, ?int $columns = null, ?int $maxWidth = null): array\",\"slug\":\"select-string-message-array-options-bool-allowmultiple-true-int-columns-null-int-maxwidth-null-array\",\"link\":\"#select-string-message-array-options-bool-allowmultiple-true-int-columns-null-int-maxwidth-null-array\",\"children\":[]}],\"readingTime\":{\"minutes\":1.15,\"words\":346},\"filePathRelative\":\"dev/question.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
