<template><div><h1 id="🌀-spinner" tabindex="-1"><a class="header-anchor" href="#🌀-spinner" aria-hidden="true">#</a> 🌀 Spinner</h1>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>The <code v-pre>Spinner</code> and <code v-pre>SpinnerFactory</code> classes are part of the <code v-pre>Ninja\Cosmic\Terminal\Spinner</code> namespace. They are used to create and manage a spinner in the terminal, which is a visual indicator of an ongoing process.</p>
<h2 id="spinner" tabindex="-1"><a class="header-anchor" href="#spinner" aria-hidden="true">#</a> Spinner</h2>
<p>The <code v-pre>Spinner</code> class is responsible for creating a spinner. It provides methods to set the spinner style, message, and padding. The spinner style is defined in the <code v-pre>spinners.json</code> file, which contains a list of predefined spinner styles.</p>
<h3 id="usage" tabindex="-1"><a class="header-anchor" href="#usage" aria-hidden="true">#</a> Usage</h3>
<p>To create a spinner, you first need to instantiate the <code v-pre>Spinner</code> class. You can optionally pass the spinner style to the constructor. If no style is provided, the default style (<code v-pre>dots13</code>) is used.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$spinner</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Spinner</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'dots13'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>You can set a message for the spinner using the <code v-pre>setMessage</code> method. This message is displayed next to the spinner.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$spinner</span><span class="token operator">-></span><span class="token function">setMessage</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Loading...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>You can also set the padding for the spinner using the <code v-pre>setPadding</code> method. The padding is the number of spaces between the spinner and the left border of the terminal.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$spinner</span><span class="token operator">-></span><span class="token function">setPadding</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>To start the spinner, you need to call the <code v-pre>callback</code> method and pass a callable that represents the process you want to indicate. The spinner will run in a separate process and will continue to display until the callable has finished executing.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$spinner</span><span class="token operator">-></span><span class="token function">callback</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// Your long-running process here...</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="spinnerfactory" tabindex="-1"><a class="header-anchor" href="#spinnerfactory" aria-hidden="true">#</a> SpinnerFactory</h2>
<p>The <code v-pre>SpinnerFactory</code> class provides static methods to create a spinner for a <code v-pre>Process</code> or a callable. It extends the <code v-pre>Spinner</code> class and inherits all its methods.</p>
<h3 id="usage-1" tabindex="-1"><a class="header-anchor" href="#usage-1" aria-hidden="true">#</a> Usage</h3>
<p>To create a spinner for a <code v-pre>Process</code>, you can use the <code v-pre>forProcess</code> method. You need to pass the <code v-pre>Process</code> instance and a message to the method.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$process</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Process</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'ls'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'-la'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">SpinnerFactory</span><span class="token operator">::</span><span class="token function">forProcess</span><span class="token punctuation">(</span><span class="token variable">$process</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Listing directory...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>To create a spinner for a callable, you can use the <code v-pre>forCallable</code> method. You need to pass the callable and a message to the method.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">SpinnerFactory</span><span class="token operator">::</span><span class="token function">forCallable</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// Your long-running process here...</span>
<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Processing data...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="configuring-the-spinners" tabindex="-1"><a class="header-anchor" href="#configuring-the-spinners" aria-hidden="true">#</a> Configuring the spinners</h2>
<p>The spinner frames are defined in the <code v-pre>spinners.json</code> file. Each spinner style is an object with two properties: <code v-pre>interval</code> and <code v-pre>frames</code>. The <code v-pre>interval</code> is the time in milliseconds between each frame, and <code v-pre>frames</code> is an array of strings that represent the frames of the spinner.</p>
</div></template>


