<template><div><h1 id="🗓️-tables" tabindex="-1"><a class="header-anchor" href="#🗓️-tables" aria-hidden="true">#</a> 🗓️ Tables</h1>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>The <code v-pre>Ninja\Cosmic\Terminal\Table</code> namespace provides a set of classes for creating and manipulating tables in the terminal. The main class is <code v-pre>Table</code>, which represents a table. Other classes in the namespace provide additional functionality, such as defining columns (<code v-pre>TableColumn</code>), manipulating column data (<code v-pre>TableManipulatorInterface</code>), and managing collections of columns (<code v-pre>ColumnCollection</code>).</p>
<h2 id="creating-a-table" tabindex="-1"><a class="header-anchor" href="#creating-a-table" aria-hidden="true">#</a> Creating a Table</h2>
<p>To create a table, you first need to instantiate the <code v-pre>Table</code> class. The constructor of the <code v-pre>Table</code> class accepts an instance of <code v-pre>ColumnCollection</code>, which represents the columns of the table.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Table</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Column<span class="token punctuation">\</span>ColumnCollection</span><span class="token punctuation">;</span>

<span class="token variable">$columns</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ColumnCollection</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$table</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Table</span><span class="token punctuation">(</span><span class="token variable">$columns</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="defining-columns" tabindex="-1"><a class="header-anchor" href="#defining-columns" aria-hidden="true">#</a> Defining Columns</h2>
<p>Columns are defined using the <code v-pre>TableColumn</code> class. The constructor of this class accepts the name of the column, the key (which is used to fetch the data from the row), and an optional color.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Column<span class="token punctuation">\</span>TableColumn</span><span class="token punctuation">;</span>

<span class="token variable">$column</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">TableColumn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Name'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'green'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You can add the column to the <code v-pre>ColumnCollection</code> using the <code v-pre>add</code> method.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$columns</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token variable">$column</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="manipulating-column-data" tabindex="-1"><a class="header-anchor" href="#manipulating-column-data" aria-hidden="true">#</a> Manipulating Column Data</h2>
<p>You can manipulate the data of a column using a manipulator. A manipulator is an object that implements the <code v-pre>TableManipulatorInterface</code>. This interface requires you to implement a <code v-pre>manipulate</code> method, which accepts a value and returns a manipulated value.</p>
<p>For example, the <code v-pre>DateManipulator</code> class converts a timestamp into a formatted date string.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Manipulator<span class="token punctuation">\</span>DateManipulator</span><span class="token punctuation">;</span>

<span class="token variable">$dateManipulator</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">DateManipulator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You can add the manipulator to a column using the <code v-pre>addManipulator</code> method.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$column</span><span class="token operator">-></span><span class="token function">addManipulator</span><span class="token punctuation">(</span><span class="token variable">$dateManipulator</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="adding-data-to-the-table" tabindex="-1"><a class="header-anchor" href="#adding-data-to-the-table" aria-hidden="true">#</a> Adding Data to the Table</h2>
<p>You can add data to the table using the <code v-pre>addRow</code> method. This method accepts an associative array, where the keys match the keys of the columns.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">addRow</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'John Doe'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'date'</span> <span class="token operator">=></span> <span class="token number">1633024862</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="rendering-the-table" tabindex="-1"><a class="header-anchor" href="#rendering-the-table" aria-hidden="true">#</a> Rendering the Table</h2>
<p>Finally, you can render the table using the <code v-pre>render</code> method.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="configuring-the-table" tabindex="-1"><a class="header-anchor" href="#configuring-the-table" aria-hidden="true">#</a> Configuring the table</h2>
<p>The appearance of the table headers can be customized by modifying the <code v-pre>TableConfig</code> object that is passed to the <code v-pre>Table</code> class. The <code v-pre>TableConfig</code> object contains various settings that control the appearance of the table, including the header.
At the time of writing, the following settings and their defaults values are available:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code>        <span class="token keyword">return</span> <span class="token punctuation">[</span>
            <span class="token string double-quoted-string">"charset"</span>        <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_CHARSET</span><span class="token punctuation">,</span> <span class="token comment">// the characters used to draw the table</span>
            <span class="token string double-quoted-string">"item_name"</span>      <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_ITEM_NAME</span><span class="token punctuation">,</span> <span class="token comment">// the name of the item in the table, defaults to "row"</span>
            <span class="token string double-quoted-string">"table_color"</span>    <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_TABLE_COLOR</span><span class="token punctuation">,</span> <span class="token comment">// the color of the table border, defaults to "white"</span>
            <span class="token string double-quoted-string">"header_color"</span>   <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_HEADER_COLOR</span><span class="token punctuation">,</span> <span class="token comment">// the color of the header text, defaults to "cyan"</span>
            <span class="token string double-quoted-string">"show_header"</span>    <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_SHOW_HEADER</span><span class="token punctuation">,</span> <span class="token comment">// whether to show the header, defaults to true</span>
            <span class="token string double-quoted-string">"padding"</span>        <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_PADDING</span><span class="token punctuation">,</span> <span class="token comment">// the padding between the terminal border and the table, defaults to 1</span>
            <span class="token string double-quoted-string">"center_content"</span> <span class="token operator">=></span> <span class="token keyword static-context">self</span><span class="token operator">::</span><span class="token constant">DEFAULT_CENTER_CONTENT</span><span class="token punctuation">,</span> <span class="token comment">// whether to center the content of the table, defaults to false</span>
        <span class="token punctuation">]</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Here's an example of how you can customize the appearance of the table headers:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Table</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>TableConfig</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Ninja<span class="token punctuation">\</span>Cosmic<span class="token punctuation">\</span>Terminal<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Column<span class="token punctuation">\</span>TableColumn</span><span class="token punctuation">;</span>

<span class="token comment">// Create a new TableConfig object with custom settings</span>
<span class="token variable">$config</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">TableConfig</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
    <span class="token string single-quoted-string">'header_color'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'blue'</span><span class="token punctuation">,</span>  <span class="token comment">// Set the color of the header to blue</span>
    <span class="token string single-quoted-string">'table_color'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'grey'</span><span class="token punctuation">,</span>  <span class="token comment">// Set the color of the table border to white</span>
    <span class="token string single-quoted-string">'padding'</span> <span class="token operator">=></span> <span class="token number">2</span><span class="token punctuation">,</span>            <span class="token comment">// Set the padding between the terminal border and the table to 2</span>
<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Create a new Table object with the custom TableConfig</span>
<span class="token variable">$table</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Table</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token variable">$config</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Add columns to the table</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">addColumn</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">TableColumn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Name'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">addColumn</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">TableColumn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Date'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'date'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Add data to the table</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">addRow</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'John Doe'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'date'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'2023-01-01'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">addRow</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'Jane Doe'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'date'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'2023-02-01'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Render the table</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In this example, the <code v-pre>header_color</code> and <code v-pre>table_color</code> settings in the <code v-pre>TableConfig</code> object are used to customize the appearance of the table headers. The <code v-pre>header_color</code> setting controls the color of the header text, and the <code v-pre>table_color</code> setting controls the table border color.</p>
<p>This will output the table to the terminal, with the data formatted according to the defined columns and manipulators.</p>
</div></template>


