export const data = JSON.parse("{\"key\":\"v-b7b74cec\",\"path\":\"/dev/terminal.html\",\"title\":\"🖥️ Terminal\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"The Terminal class, part of the Ninja\\\\Cosmic\\\\Terminal namespace, is a central component of the application. It provides a set of static methods for interacting with the terminal...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/terminal.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Cosmic PHP - Documentation\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🖥️ Terminal\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"The Terminal class, part of the Ninja\\\\Cosmic\\\\Terminal namespace, is a central component of the application. It provides a set of static methods for interacting with the terminal...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Diego Rin Martín\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🖥️ Terminal\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Diego Rin Martín\\\",\\\"url\\\":\\\"https://diego.ninja\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Overview\",\"slug\":\"overview\",\"link\":\"#overview\",\"children\":[]},{\"level\":2,\"title\":\"Usage\",\"slug\":\"usage\",\"link\":\"#usage\",\"children\":[{\"level\":3,\"title\":\"Outputting Text\",\"slug\":\"outputting-text\",\"link\":\"#outputting-text\",\"children\":[]},{\"level\":3,\"title\":\"Asking Questions\",\"slug\":\"asking-questions\",\"link\":\"#asking-questions\",\"children\":[]},{\"level\":3,\"title\":\"Confirming Actions\",\"slug\":\"confirming-actions\",\"link\":\"#confirming-actions\",\"children\":[]},{\"level\":3,\"title\":\"Selecting Options\",\"slug\":\"selecting-options\",\"link\":\"#selecting-options\",\"children\":[]},{\"level\":3,\"title\":\"Displaying Tables\",\"slug\":\"displaying-tables\",\"link\":\"#displaying-tables\",\"children\":[]}]},{\"level\":2,\"title\":\"Themes\",\"slug\":\"themes\",\"link\":\"#themes\",\"children\":[]},{\"level\":2,\"title\":\"Sections\",\"slug\":\"sections\",\"link\":\"#sections\",\"children\":[]},{\"level\":2,\"title\":\"Resetting the Terminal\",\"slug\":\"resetting-the-terminal\",\"link\":\"#resetting-the-terminal\",\"children\":[]},{\"level\":2,\"title\":\"Rendering Text\",\"slug\":\"rendering-text\",\"link\":\"#rendering-text\",\"children\":[]},{\"level\":2,\"title\":\"Color Styles\",\"slug\":\"color-styles\",\"link\":\"#color-styles\",\"children\":[]}],\"readingTime\":{\"minutes\":2.16,\"words\":647},\"filePathRelative\":\"dev/terminal.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
