<template><div><h1 id="🖥️-terminal" tabindex="-1"><a class="header-anchor" href="#🖥️-terminal" aria-hidden="true">#</a> 🖥️ Terminal</h1>
<p>The <code v-pre>Terminal</code> class, part of the <code v-pre>Ninja\Cosmic\Terminal</code> namespace, is a central component of the application. It provides a set of static methods for interacting with the terminal, including outputting text, asking questions, confirming actions, selecting options, and displaying tables.</p>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>The <code v-pre>Terminal</code> class is a singleton, meaning there can only be one instance of it at any given time. This instance can be retrieved using the <code v-pre>getInstance</code> method.</p>
<p>The <code v-pre>Terminal</code> class uses the <code v-pre>ThemeLoader</code> class to manage themes, which control the appearance of the terminal output. Themes can be loaded from a directory, added individually, and enabled by name.</p>
<p>The <code v-pre>Terminal</code> class also provides methods for outputting text to the terminal (<code v-pre>output</code>), reading input from the terminal (<code v-pre>input</code>), and managing sections of the terminal output (<code v-pre>header</code>, <code v-pre>body</code>, <code v-pre>footer</code>).</p>
<h2 id="usage" tabindex="-1"><a class="header-anchor" href="#usage" aria-hidden="true">#</a> Usage</h2>
<h3 id="outputting-text" tabindex="-1"><a class="header-anchor" href="#outputting-text" aria-hidden="true">#</a> Outputting Text</h3>
<p>To output text to the terminal, you can use the <code v-pre>output</code> method. This method returns an instance of <code v-pre>ConsoleOutput</code>, which you can use to write text to the terminal.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Hello, world!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="asking-questions" tabindex="-1"><a class="header-anchor" href="#asking-questions" aria-hidden="true">#</a> Asking Questions</h3>
<p>To ask a question in the terminal, you can use the <code v-pre>ask</code> method. This method prompts the user for input and returns their response.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$name</span> <span class="token operator">=</span> <span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">ask</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'What is your name?'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string double-quoted-string">"Hello, <span class="token interpolation"><span class="token variable">$name</span></span>!"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="confirming-actions" tabindex="-1"><a class="header-anchor" href="#confirming-actions" aria-hidden="true">#</a> Confirming Actions</h3>
<p>To confirm an action in the terminal, you can use the <code v-pre>confirm</code> method. This method prompts the user for a yes/no response and returns a boolean indicating their choice.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">confirm</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Are you sure you want to continue?'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Continuing...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
    <span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Aborting...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="selecting-options" tabindex="-1"><a class="header-anchor" href="#selecting-options" aria-hidden="true">#</a> Selecting Options</h3>
<p>To prompt the user to select an option from a list, you can use the <code v-pre>select</code> method. This method displays a list of options in the terminal and returns the user's selection(s).</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$color</span> <span class="token operator">=</span> <span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">select</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Choose a color:'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'Red'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Green'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Blue'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string double-quoted-string">"You chose: <span class="token interpolation"><span class="token variable">$color</span></span>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="displaying-tables" tabindex="-1"><a class="header-anchor" href="#displaying-tables" aria-hidden="true">#</a> Displaying Tables</h3>
<p>To display a table in the terminal, you can use the <code v-pre>table</code> method. This method accepts an array of headers and an array of data, and it displays the data in a table format in the terminal.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$headers</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'Name'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Age'</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token variable">$data</span> <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string single-quoted-string">'John Doe'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string single-quoted-string">'Jane Doe'</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">table</span><span class="token punctuation">(</span><span class="token variable">$headers</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="themes" tabindex="-1"><a class="header-anchor" href="#themes" aria-hidden="true">#</a> Themes</h2>
<p>The <code v-pre>Terminal</code> class uses the <code v-pre>ThemeLoader</code> class to manage themes. Themes control the appearance of the terminal output, including colors, styles, and icons.</p>
<p>You can load themes from a directory using the <code v-pre>loadThemes</code> method, add individual themes using the <code v-pre>addTheme</code> method, and enable a theme using the <code v-pre>enableTheme</code> method.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// Load themes from a directory</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">loadThemes</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'/path/to/themes'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Add an individual theme</span>
<span class="token variable">$theme</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">MyTheme</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">addTheme</span><span class="token punctuation">(</span><span class="token variable">$theme</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Enable a theme</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">enableTheme</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'my-theme'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sections" tabindex="-1"><a class="header-anchor" href="#sections" aria-hidden="true">#</a> Sections</h2>
<p>The <code v-pre>Terminal</code> class provides methods for managing sections of the terminal output. These sections can be used to organize the output into separate areas, such as a header, a body, and a footer.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// Write to the header section</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">header</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'This is the header.'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Write to the body section</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">body</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'This is the body.'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Write to the footer section</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">footer</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'This is the footer.'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="resetting-the-terminal" tabindex="-1"><a class="header-anchor" href="#resetting-the-terminal" aria-hidden="true">#</a> Resetting the Terminal</h2>
<p>To clear the terminal, you can use the <code v-pre>reset</code> method. This method clears all output from the terminal.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">reset</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="rendering-text" tabindex="-1"><a class="header-anchor" href="#rendering-text" aria-hidden="true">#</a> Rendering Text</h2>
<p>To format text according to the current theme, you can use the <code v-pre>render</code> method. This method accepts a string of text and returns a string of text formatted according to the current theme.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$formattedText</span> <span class="token operator">=</span> <span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">render</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'&lt;info>This is some informational text.&lt;/info>'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token variable">$formattedText</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="color-styles" tabindex="-1"><a class="header-anchor" href="#color-styles" aria-hidden="true">#</a> Color Styles</h2>
<p>To retrieve a color style defined in the current theme, you can use the <code v-pre>color</code> method. This method accepts the name of a color style and returns an <code v-pre>OutputFormatterStyleInterface</code> object representing the color style.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$style</span> <span class="token operator">=</span> <span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">color</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'info'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$formattedText</span> <span class="token operator">=</span> <span class="token variable">$style</span><span class="token operator">-></span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'This is some informational text.'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">output</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">writeln</span><span class="token punctuation">(</span><span class="token variable">$formattedText</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


