<template><div><h1 id="🌈-writing-terminal-themes-draft" tabindex="-1"><a class="header-anchor" href="#🌈-writing-terminal-themes-draft" aria-hidden="true">#</a> 🌈 Writing terminal themes (DRAFT)</h1>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>Themes are used to customize the appearance of the terminal output. A theme is an object that implements the <code v-pre>ThemeInterface</code> and provides a set of styles that are used by the <code v-pre>Terminal</code> class to format its output.</p>
<h2 id="creating-a-theme" tabindex="-1"><a class="header-anchor" href="#creating-a-theme" aria-hidden="true">#</a> Creating a theme</h2>
<p>A theme is a set of files inside a folder, at the time of writing this document, a theme is composed by three files, the default theme folder is /themes, but you can load themes from any folder. The applications generated with the cosmic binary loads all themes inside the /themes folders automatically.</p>
<p>This three files must reside inside a folder named as the theme, so, for example, the included theme alien, is inside the folder /themes/alien</p>
<h3 id="theme-json" tabindex="-1"><a class="header-anchor" href="#theme-json" aria-hidden="true">#</a> theme.json</h3>
<p>This is the real theme definition file, it is a free json file, and free means that it has no schema to conform to, schema enforcement is in the roadmap for the next versions of Cosmic, but for now at least you need to define the following sections, in addition to the name, description and other metadata values defined in the root of the json object:</p>
<h4 id="colors" tabindex="-1"><a class="header-anchor" href="#colors" aria-hidden="true">#</a> colors</h4>
<p>This section defines the color scheme for the theme. Each key-value pair represents a specific text type (such as <code v-pre>text</code>, <code v-pre>comment</code>, <code v-pre>info</code>, etc.) and its corresponding color in hexadecimal format. The regular definition is in the form key-value, where the key is the name of the color and the value is its hexadecimal representation, but you can use an extended notation that instead of the hexadecimal color representation uses an array consisting of three elements, fg for foreground color, bg for background color, and options for additional attributes that define the color style such as bold or blink.</p>
<p>The colors are loaded into the default OutputInterface in the application and they are defined as termwind custom styles too. (Termwind style just load the simple notation colors)</p>
<p>You can define as many colors as you want, but at least, the following set of colors must be present in every terminal theme.</p>
<div class="language-json line-numbers-mode" data-ext="json"><pre v-pre class="language-json"><code><span class="token property">"colors"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
    <span class="token property">"text"</span><span class="token operator">:</span> <span class="token string">"#E5E9F0"</span><span class="token punctuation">,</span>  
    <span class="token property">"comment"</span><span class="token operator">:</span> <span class="token string">"#EBCB8B"</span><span class="token punctuation">,</span>  
    <span class="token property">"info"</span><span class="token operator">:</span> <span class="token string">"#81A1C1"</span><span class="token punctuation">,</span>  
    <span class="token property">"notice"</span><span class="token operator">:</span> <span class="token string">"#8FBCBB"</span><span class="token punctuation">,</span>  
    <span class="token property">"warning"</span><span class="token operator">:</span> <span class="token string">"#D08770"</span><span class="token punctuation">,</span>  
    <span class="token property">"error"</span><span class="token operator">:</span> <span class="token string">"#BF616A"</span><span class="token punctuation">,</span>  
    <span class="token property">"success"</span><span class="token operator">:</span> <span class="token string">"#A3BE8C"</span><span class="token punctuation">,</span>  
    <span class="token property">"white"</span><span class="token operator">:</span> <span class="token string">"#FFFFFF"</span><span class="token punctuation">,</span>  
    <span class="token property">"black"</span><span class="token operator">:</span> <span class="token string">"#000000"</span><span class="token punctuation">,</span>  
    <span class="token property">"grey"</span><span class="token operator">:</span> <span class="token string">"#4C566A"</span><span class="token punctuation">,</span>  
    <span class="token property">"red"</span><span class="token operator">:</span> <span class="token string">"#BF616A"</span><span class="token punctuation">,</span>  
    <span class="token property">"green"</span><span class="token operator">:</span> <span class="token string">"#A3BE8C"</span><span class="token punctuation">,</span>  
    <span class="token property">"yellow"</span><span class="token operator">:</span> <span class="token string">"#EBCB8B"</span><span class="token punctuation">,</span>  
    <span class="token property">"blue"</span><span class="token operator">:</span> <span class="token string">"#81A1C1"</span><span class="token punctuation">,</span>  
    <span class="token property">"purple"</span><span class="token operator">:</span> <span class="token string">"#B48EAD"</span><span class="token punctuation">,</span>  
    <span class="token property">"cyan"</span><span class="token operator">:</span> <span class="token string">"#88C0D0"</span><span class="token punctuation">,</span>  
    <span class="token property">"hl"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
        <span class="token property">"fg"</span><span class="token operator">:</span> <span class="token string">"#E5E9F0"</span><span class="token punctuation">,</span>  
        <span class="token property">"bg"</span><span class="token operator">:</span> <span class="token string">"#4C566A"</span>  
    <span class="token punctuation">}</span><span class="token punctuation">,</span>  
    <span class="token property">"critical"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
        <span class="token property">"fg"</span><span class="token operator">:</span> <span class="token string">"#BF616A"</span><span class="token punctuation">,</span>  
        <span class="token property">"options"</span><span class="token operator">:</span> <span class="token punctuation">[</span>  
            <span class="token string">"blink"</span>  
        <span class="token punctuation">]</span>  
    <span class="token punctuation">}</span><span class="token punctuation">,</span>    <span class="token property">"warn"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
        <span class="token property">"fg"</span><span class="token operator">:</span> <span class="token string">"#D08770"</span><span class="token punctuation">,</span>  
        <span class="token property">"options"</span><span class="token operator">:</span> <span class="token punctuation">[</span>  
            <span class="token string">"blink"</span>  
        <span class="token punctuation">]</span>  
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="icons" tabindex="-1"><a class="header-anchor" href="#icons" aria-hidden="true">#</a> icons</h4>
<p>This section defines various icons used in the terminal. Each key-value pair represents a specific type of icon (like <code v-pre>application</code>, <code v-pre>bullet</code>, <code v-pre>success</code>, etc.) and its corresponding character representation. You can define as many icons as you want, but at least the following set of icons must be present in every theme, directly or extending another theme.</p>
<div class="language-json line-numbers-mode" data-ext="json"><pre v-pre class="language-json"><code><span class="token property">"icons"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
    <span class="token property">"application"</span><span class="token operator">:</span> <span class="token string">"🚀"</span><span class="token punctuation">,</span>  
    <span class="token property">"bullet"</span><span class="token operator">:</span> <span class="token string">"⬢"</span><span class="token punctuation">,</span>  
    <span class="token property">"success"</span><span class="token operator">:</span> <span class="token string">"⬡"</span><span class="token punctuation">,</span>  
    <span class="token property">"failure"</span><span class="token operator">:</span> <span class="token string">"⬡"</span><span class="token punctuation">,</span>  
    <span class="token property">"radio_selected"</span><span class="token operator">:</span> <span class="token string">"⬢"</span><span class="token punctuation">,</span>  
    <span class="token property">"radio"</span><span class="token operator">:</span> <span class="token string">"⬡"</span><span class="token punctuation">,</span>  
    <span class="token property">"checkbox"</span><span class="token operator">:</span> <span class="token string">"☐"</span><span class="token punctuation">,</span>  
    <span class="token property">"checkbox_selected"</span><span class="token operator">:</span> <span class="token string">"✔"</span>  
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="styles" tabindex="-1"><a class="header-anchor" href="#styles" aria-hidden="true">#</a> styles</h4>
<p>This section defines various styles used in the terminal. Each key-value pair represents a specific type of style (like <code v-pre>container</code>, <code v-pre>footer</code>, <code v-pre>emphasis</code>, etc.) and its corresponding CSS class names. This styles are just only loaded as Termwind styles and are mainly used to render the command help markdown files using the console.</p>
<p>As in prior sections, you can define as many Termwind styles as you want, but the minimal set of styles required to properly render the command help files is as follows:</p>
<div class="language-json line-numbers-mode" data-ext="json"><pre v-pre class="language-json"><code><span class="token property">"styles"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
    <span class="token property">"container"</span><span class="token operator">:</span> <span class="token string">"w-120 ml-2"</span><span class="token punctuation">,</span>  
    <span class="token property">"footer"</span><span class="token operator">:</span> <span class="token string">"w-120 pt-2 ml-2"</span><span class="token punctuation">,</span>  
    <span class="token property">"emphasis"</span><span class="token operator">:</span> <span class="token string">"font-bold text-yellow italic"</span><span class="token punctuation">,</span>  
    <span class="token property">"strong"</span><span class="token operator">:</span> <span class="token string">"font-bold text-blue"</span><span class="token punctuation">,</span>  
    <span class="token property">"strike"</span><span class="token operator">:</span> <span class="token string">"line-through"</span><span class="token punctuation">,</span>  
    <span class="token property">"hr"</span><span class="token operator">:</span> <span class="token string">"text-blue"</span><span class="token punctuation">,</span>  
    <span class="token property">"h1"</span><span class="token operator">:</span> <span class="token string">"invisible"</span><span class="token punctuation">,</span>  
    <span class="token property">"heading"</span><span class="token operator">:</span> <span class="token string">"text-blue pt-1"</span><span class="token punctuation">,</span>  
    <span class="token property">"language-sh"</span><span class="token operator">:</span> <span class="token string">"w-120"</span><span class="token punctuation">,</span>  
    <span class="token property">"language-php"</span><span class="token operator">:</span> <span class="token string">"w-120"</span><span class="token punctuation">,</span>  
    <span class="token property">"language-js"</span><span class="token operator">:</span> <span class="token string">"w-120"</span><span class="token punctuation">,</span>  
    <span class="token property">"language-sql"</span><span class="token operator">:</span> <span class="token string">"w-120"</span><span class="token punctuation">,</span>  
    <span class="token property">"language"</span><span class="token operator">:</span> <span class="token string">"w-120"</span><span class="token punctuation">,</span>  
    <span class="token property">"link"</span><span class="token operator">:</span> <span class="token string">"text-blue underline"</span><span class="token punctuation">,</span>  
    <span class="token property">"app-icon"</span><span class="token operator">:</span> <span class="token string">"mr-1"</span><span class="token punctuation">,</span>  
    <span class="token property">"question"</span><span class="token operator">:</span> <span class="token string">"text-blue"</span><span class="token punctuation">,</span>  
    <span class="token property">"default-option"</span><span class="token operator">:</span> <span class="token string">"font-bold text-yellow"</span>  
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="config" tabindex="-1"><a class="header-anchor" href="#config" aria-hidden="true">#</a> config</h4>
<p>This section holds miscellaneous configuration used along the application, at the time of writing this document,  you can define here as many config values as you want,  the only required configuration is the one exposed in the following code excerpt:</p>
<div class="language-json line-numbers-mode" data-ext="json"><pre v-pre class="language-json"><code><span class="token property">"config"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
    <span class="token property">"icons_enabled"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>  
    <span class="token property">"table"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
        <span class="token property">"charset"</span><span class="token operator">:</span> <span class="token punctuation">{</span>  
            <span class="token property">"top"</span><span class="token operator">:</span> <span class="token string">"═"</span><span class="token punctuation">,</span>  
            <span class="token property">"top-mid"</span><span class="token operator">:</span> <span class="token string">"╤"</span><span class="token punctuation">,</span>  
            <span class="token property">"top-left"</span><span class="token operator">:</span> <span class="token string">"╔"</span><span class="token punctuation">,</span>  
            <span class="token property">"top-right"</span><span class="token operator">:</span> <span class="token string">"╗"</span><span class="token punctuation">,</span>  
            <span class="token property">"bottom"</span><span class="token operator">:</span> <span class="token string">"═"</span><span class="token punctuation">,</span>  
            <span class="token property">"bottom-mid"</span><span class="token operator">:</span> <span class="token string">"╧"</span><span class="token punctuation">,</span>  
            <span class="token property">"bottom-left"</span><span class="token operator">:</span> <span class="token string">"╚"</span><span class="token punctuation">,</span>  
            <span class="token property">"bottom-right"</span><span class="token operator">:</span> <span class="token string">"╝"</span><span class="token punctuation">,</span>  
            <span class="token property">"left"</span><span class="token operator">:</span> <span class="token string">"║"</span><span class="token punctuation">,</span>  
            <span class="token property">"left-mid"</span><span class="token operator">:</span> <span class="token string">"╟"</span><span class="token punctuation">,</span>  
            <span class="token property">"mid"</span><span class="token operator">:</span> <span class="token string">"─"</span><span class="token punctuation">,</span>  
            <span class="token property">"mid-mid"</span><span class="token operator">:</span> <span class="token string">"┼"</span><span class="token punctuation">,</span>  
            <span class="token property">"right"</span><span class="token operator">:</span> <span class="token string">"║"</span><span class="token punctuation">,</span>  
            <span class="token property">"right-mid"</span><span class="token operator">:</span> <span class="token string">"╢"</span><span class="token punctuation">,</span>  
            <span class="token property">"middle"</span><span class="token operator">:</span> <span class="token string">"│"</span>  
        <span class="token punctuation">}</span><span class="token punctuation">,</span>  
        <span class="token property">"table_color"</span><span class="token operator">:</span> <span class="token string">"white"</span><span class="token punctuation">,</span>  
        <span class="token property">"header_color"</span><span class="token operator">:</span> <span class="token string">"cyan"</span><span class="token punctuation">,</span>  
        <span class="token property">"field_color"</span><span class="token operator">:</span> <span class="token string">"white"</span>  
    <span class="token punctuation">}</span>  
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You can use the default theme as guide when you need to define a new theme,</p>
<h3 id="notification-png" tabindex="-1"><a class="header-anchor" href="#notification-png" aria-hidden="true">#</a> notification.png</h3>
<p>This file is used when displaying an os-based notification using the Notifier class, the recomended settings for this file is an PNG image of width and height of 512px and transparent background.</p>
<h3 id="logo-php" tabindex="-1"><a class="header-anchor" href="#logo-php" aria-hidden="true">#</a> logo.php</h3>
<p>This file is a PHP script that returns a string containing ANSI escape codes. These codes are used to format text in a terminal, allowing for things like color changes and cursor movements. It represents the colorful banner with the app logo that is displayed when the about command is executed</p>
<p>To generate a file like this, you would need to design your logo or banner using characters and spaces, then add ANSI escape codes to colorize it. There are online tools available that can help you design ANSI art and generate the corresponding escape codes.</p>
<p>The recommended way for generating application ANSI logos is to use the following site with the Unicode + True Color options enabled:</p>
<p><a href="https://dom111.github.io/image-to-ansi/" target="_blank" rel="noopener noreferrer">Image to ANSI<ExternalLinkIcon/></a></p>
<p>🤓 PRO TIP: If you convert your notification icon into an ANSI logo using the above site, you can use the same image for both the logo and the notification icon, giving your application a consistent look.</p>
<h2 id="extending-a-theme" tabindex="-1"><a class="header-anchor" href="#extending-a-theme" aria-hidden="true">#</a> Extending a theme</h2>
<p>TBA</p>
<h2 id="enabling-a-theme-at-runtime" tabindex="-1"><a class="header-anchor" href="#enabling-a-theme-at-runtime" aria-hidden="true">#</a> Enabling a Theme at Runtime</h2>
<p>To enable a theme at runtime, you can use the <code v-pre>Terminal::withTheme</code> method and pass an instance of your theme. This will set the theme for the current <code v-pre>Terminal</code> instance.</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">Terminal</span><span class="token operator">::</span><span class="token function">withTheme</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">MyTheme</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="the-theme-global-parameter" tabindex="-1"><a class="header-anchor" href="#the-theme-global-parameter" aria-hidden="true">#</a> The <code v-pre>--theme</code> Global Parameter</h2>
<p>The <code v-pre>--theme</code> global parameter allows you to specify the theme to use when running the application from the command line. This overrides the theme set in the environment variable.</p>
<p>To use this parameter, pass it to the application with the name of your theme:</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>php my-app.php <span class="token parameter variable">--theme</span><span class="token operator">=</span>my-theme
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The application will then use the specified theme for its output. If the theme does not exist, the application will fall back to the default theme.</p>
<h2 id="themeloader" tabindex="-1"><a class="header-anchor" href="#themeloader" aria-hidden="true">#</a> ThemeLoader</h2>
<p>The <code v-pre>ThemeLoader</code> class is responsible for managing the themes in the application. It provides methods to add a theme (<code v-pre>addTheme</code>), enable a theme (<code v-pre>enableTheme</code>), and get the currently enabled theme (<code v-pre>getEnabledTheme</code>). It also provides a method to load all themes from a directory (<code v-pre>loadDirectory</code>), which can be useful if you have multiple theme classes in your project.</p>
<p>To add a theme to the <code v-pre>ThemeLoader</code>, you can use the <code v-pre>addTheme</code> method and pass an instance of your theme:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">ThemeLoader</span><span class="token operator">::</span><span class="token function">addTheme</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">MyTheme</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>To enable a theme, you can use the <code v-pre>enableTheme</code> method and pass the name of your theme:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">ThemeLoader</span><span class="token operator">::</span><span class="token function">enableTheme</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'my-theme'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The <code v-pre>getEnabledTheme</code> method returns the currently enabled theme:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$theme</span> <span class="token operator">=</span> <span class="token class-name static-context">ThemeLoader</span><span class="token operator">::</span><span class="token function">getEnabledTheme</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The <code v-pre>loadDirectory</code> method loads all theme classes from a specified directory:</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">ThemeLoader</span><span class="token operator">::</span><span class="token function">loadDirectory</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'/path/to/themes'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>This method uses the PHP <code v-pre>glob</code> function to find all PHP files in the specified directory, and then it includes each file and adds the theme to the <code v-pre>ThemeLoader</code>. The theme classes in the directory should be defined in the global namespace and their names should match their file names.</p>
</div></template>


