export const data = JSON.parse("{\"key\":\"v-25572cda\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Installer/AbstractInstaller.html\",\"title\":\"AbstractInstaller\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Class AbstractInstaller An abstract base class implementing the InstallerInterface with common functionality. Full name: \\\\Ninja\\\\Cosmic\\\\Installer\\\\AbstractInstaller; This class im...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Installer/AbstractInstaller.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"AbstractInstaller\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Class AbstractInstaller An abstract base class implementing the InstallerInterface with common functionality. Full name: \\\\Ninja\\\\Cosmic\\\\Installer\\\\AbstractInstaller; This class im...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"AbstractInstaller\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Properties\",\"slug\":\"properties\",\"link\":\"#properties\",\"children\":[{\"level\":3,\"title\":\"packages\",\"slug\":\"packages\",\"link\":\"#packages\",\"children\":[]},{\"level\":3,\"title\":\"pre_install\",\"slug\":\"pre-install\",\"link\":\"#pre-install\",\"children\":[]},{\"level\":3,\"title\":\"post_install\",\"slug\":\"post-install\",\"link\":\"#post-install\",\"children\":[]},{\"level\":3,\"title\":\"is_installed\",\"slug\":\"is-installed\",\"link\":\"#is-installed\",\"children\":[]},{\"level\":3,\"title\":\"output\",\"slug\":\"output\",\"link\":\"#output\",\"children\":[]}]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"__construct\",\"slug\":\"construct\",\"link\":\"#construct\",\"children\":[]},{\"level\":3,\"title\":\"preInstall\",\"slug\":\"preinstall\",\"link\":\"#preinstall\",\"children\":[]},{\"level\":3,\"title\":\"postInstall\",\"slug\":\"postinstall\",\"link\":\"#postinstall\",\"children\":[]},{\"level\":3,\"title\":\"isInstalled\",\"slug\":\"isinstalled\",\"link\":\"#isinstalled\",\"children\":[]},{\"level\":3,\"title\":\"addPackage\",\"slug\":\"addpackage\",\"link\":\"#addpackage\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.88,\"words\":265},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Installer/AbstractInstaller.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
