export const data = JSON.parse("{\"key\":\"v-64f2fd56\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Installer/AptInstaller.html\",\"title\":\"AptInstaller\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Class AptInstaller An installer implementation for Debian-based systems using apt package manager. Full name: \\\\Ninja\\\\Cosmic\\\\Installer\\\\AptInstaller; Parent class: \\\\Ninja\\\\Cosmic\\\\I...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Installer/AptInstaller.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"AptInstaller\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Class AptInstaller An installer implementation for Debian-based systems using apt package manager. Full name: \\\\Ninja\\\\Cosmic\\\\Installer\\\\AptInstaller; Parent class: \\\\Ninja\\\\Cosmic\\\\I...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"AptInstaller\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"isPackageInstalled\",\"slug\":\"ispackageinstalled\",\"link\":\"#ispackageinstalled\",\"children\":[]},{\"level\":3,\"title\":\"install\",\"slug\":\"install\",\"link\":\"#install\",\"children\":[]},{\"level\":3,\"title\":\"updateApt\",\"slug\":\"updateapt\",\"link\":\"#updateapt\",\"children\":[]}]},{\"level\":2,\"title\":\"Inherited methods\",\"slug\":\"inherited-methods\",\"link\":\"#inherited-methods\",\"children\":[{\"level\":3,\"title\":\"__construct\",\"slug\":\"construct\",\"link\":\"#construct\",\"children\":[]},{\"level\":3,\"title\":\"preInstall\",\"slug\":\"preinstall\",\"link\":\"#preinstall\",\"children\":[]},{\"level\":3,\"title\":\"postInstall\",\"slug\":\"postinstall\",\"link\":\"#postinstall\",\"children\":[]},{\"level\":3,\"title\":\"isInstalled\",\"slug\":\"isinstalled\",\"link\":\"#isinstalled\",\"children\":[]},{\"level\":3,\"title\":\"addPackage\",\"slug\":\"addpackage\",\"link\":\"#addpackage\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.95,\"words\":284},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Installer/AptInstaller.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
