export const data = JSON.parse("{\"key\":\"v-187ca70f\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Serializer/DeserializableTrait.html\",\"title\":\"DeserializableTrait\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Serializer\\\\DeserializableTrait; Methods fromArray This method is static.; Parameters: Parameter Type Description ------------------------------ $data ar...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Serializer/DeserializableTrait.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"DeserializableTrait\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Serializer\\\\DeserializableTrait; Methods fromArray This method is static.; Parameters: Parameter Type Description ------------------------------ $data ar...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"DeserializableTrait\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"fromArray\",\"slug\":\"fromarray\",\"link\":\"#fromarray\",\"children\":[]},{\"level\":3,\"title\":\"fromJson\",\"slug\":\"fromjson\",\"link\":\"#fromjson\",\"children\":[]},{\"level\":3,\"title\":\"getPropertyType\",\"slug\":\"getpropertytype\",\"link\":\"#getpropertytype\",\"children\":[]},{\"level\":3,\"title\":\"isPropertyNullable\",\"slug\":\"ispropertynullable\",\"link\":\"#ispropertynullable\",\"children\":[]},{\"level\":3,\"title\":\"hasMethod\",\"slug\":\"hasmethod\",\"link\":\"#hasmethod\",\"children\":[]},{\"level\":3,\"title\":\"isDateTime\",\"slug\":\"isdatetime\",\"link\":\"#isdatetime\",\"children\":[]},{\"level\":3,\"title\":\"getNormalizedValue\",\"slug\":\"getnormalizedvalue\",\"link\":\"#getnormalizedvalue\",\"children\":[]},{\"level\":3,\"title\":\"getDateTimeObject\",\"slug\":\"getdatetimeobject\",\"link\":\"#getdatetimeobject\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.55,\"words\":166},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Serializer/DeserializableTrait.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
