export const data = JSON.parse("{\"key\":\"v-0af67da9\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Terminal/Theme/Element/Spinner/Spinner.html\",\"title\":\"Spinner\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\Spinner\\\\Spinner; Parent class: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\AbstractThemeElement (../AbstractThemeElement.md); Properties...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Terminal/Theme/Element/Spinner/Spinner.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Spinner\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\Spinner\\\\Spinner; Parent class: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\Element\\\\AbstractThemeElement (../AbstractThemeElement.md); Properties...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Spinner\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Properties\",\"slug\":\"properties\",\"link\":\"#properties\",\"children\":[{\"level\":3,\"title\":\"name\",\"slug\":\"name\",\"link\":\"#name\",\"children\":[]},{\"level\":3,\"title\":\"frames\",\"slug\":\"frames\",\"link\":\"#frames\",\"children\":[]},{\"level\":3,\"title\":\"interval\",\"slug\":\"interval\",\"link\":\"#interval\",\"children\":[]}]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"__construct\",\"slug\":\"construct\",\"link\":\"#construct\",\"children\":[]},{\"level\":3,\"title\":\"fromArray\",\"slug\":\"fromarray\",\"link\":\"#fromarray\",\"children\":[]}]},{\"level\":2,\"title\":\"Inherited methods\",\"slug\":\"inherited-methods\",\"link\":\"#inherited-methods\",\"children\":[{\"level\":3,\"title\":\"toJson\",\"slug\":\"tojson\",\"link\":\"#tojson\",\"children\":[]},{\"level\":3,\"title\":\"toArray\",\"slug\":\"toarray\",\"link\":\"#toarray\",\"children\":[]},{\"level\":3,\"title\":\"jsonSerialize\",\"slug\":\"jsonserialize\",\"link\":\"#jsonserialize\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.36,\"words\":108},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Terminal/Theme/Element/Spinner/Spinner.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
