export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"a","t":""},["/README.md"]],
  ["v-6ce48554","/contributing.html",{"y":"a","t":""},[":md"]],
  ["v-11a5a1f8","/credits.html",{"y":"a","t":""},[":md"]],
  ["v-2cf9e463","/features.html",{"y":"a","t":""},[":md"]],
  ["v-6ca815f4","/installation.html",{"y":"a","t":"📦 Installation"},[":md"]],
  ["v-718e40a7","/overview.html",{"y":"a","t":"🛸 Overview"},[":md"]],
  ["v-4b882c70","/requirements.html",{"y":"a","t":"✋ Requirements"},[":md"]],
  ["v-646b6f91","/usage.html",{"y":"a","t":"🧰 Basic usage"},[":md"]],
  ["v-a4825818","/dev/01_application.html",{"y":"a","t":"🛸 Creating a new application"},[":md"]],
  ["v-4951bf07","/dev/02_commands.html",{"y":"a","t":"🛠️ Adding commands"},[":md"]],
  ["v-57a9a3a2","/dev/lifecycle.html",{"y":"a","t":"🔫 Lifecycle Events"},[":md"]],
  ["v-07fcf938","/dev/notifications.html",{"y":"a","t":"💬 Notifications"},[":md"]],
  ["v-6c4f8f13","/dev/spinner.html",{"y":"a","t":"🌀 Spinner"},[":md"]],
  ["v-aa4382fe","/dev/tables.html",{"y":"a","t":"🗓️ Tables"},[":md"]],
  ["v-b7b74cec","/dev/terminal.html",{"y":"a","t":"🖥️ Terminal"},[":md"]],
  ["v-34943c35","/dev/api/facades/question.html",{"y":"a","t":"📝 Question Facade"},[":md"]],
  ["v-bb65a072","/dev/api/facades/ui.html",{"y":"a","t":"🪄 UI Facade"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-7445cd33","/dev/",{"y":"p","t":"Dev"},[]],
  ["v-3b8c3d3e","/dev/api/facades/",{"y":"p","t":"Facades"},[]],
  ["v-1593c508","/dev/api/",{"y":"p","t":"Api"},[]],
  ["v-945bc308","/dev/api/helpers.html",{"y":"a","t":"🛟 Helpers Documentation"},[":md"]],
  ["v-ffdf09f4","/dev/03_themes.html",{"y":"a","t":"🌈 Writing terminal themes (DRAFT)"},[":md"]],
]
