export const data = JSON.parse("{\"key\":\"v-41c6b686\",\"path\":\"/dev/api/classes/Ninja/Cosmic/Terminal/Theme/ThemeLoader.html\",\"title\":\"ThemeLoader\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\ThemeLoader; This class is marked as final and can't be subclassed; This class implements:; \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\ThemeLoaderInter...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/api/classes/Ninja/Cosmic/Terminal/Theme/ThemeLoader.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ThemeLoader\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Full name: \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\ThemeLoader; This class is marked as final and can't be subclassed; This class implements:; \\\\Ninja\\\\Cosmic\\\\Terminal\\\\Theme\\\\ThemeLoaderInter...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ThemeLoader\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Properties\",\"slug\":\"properties\",\"link\":\"#properties\",\"children\":[{\"level\":3,\"title\":\"theme\",\"slug\":\"theme\",\"link\":\"#theme\",\"children\":[]},{\"level\":3,\"title\":\"themes\",\"slug\":\"themes\",\"link\":\"#themes\",\"children\":[]},{\"level\":3,\"title\":\"output\",\"slug\":\"output\",\"link\":\"#output\",\"children\":[]}]},{\"level\":2,\"title\":\"Methods\",\"slug\":\"methods\",\"link\":\"#methods\",\"children\":[{\"level\":3,\"title\":\"__construct\",\"slug\":\"construct\",\"link\":\"#construct\",\"children\":[]},{\"level\":3,\"title\":\"loadDirectory\",\"slug\":\"loaddirectory\",\"link\":\"#loaddirectory\",\"children\":[]},{\"level\":3,\"title\":\"addTheme\",\"slug\":\"addtheme\",\"link\":\"#addtheme\",\"children\":[]},{\"level\":3,\"title\":\"getEnabledTheme\",\"slug\":\"getenabledtheme\",\"link\":\"#getenabledtheme\",\"children\":[]},{\"level\":3,\"title\":\"enableTheme\",\"slug\":\"enabletheme\",\"link\":\"#enabletheme\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.51,\"words\":153},\"filePathRelative\":\"dev/api/classes/Ninja/Cosmic/Terminal/Theme/ThemeLoader.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
